### ISSUE TITLE
Theme causes black borders in System Monitor

### ISSUE THREAD

**Issue by dignakov** [bsundman/Yosembiance#1]
The themse (Yosembiane/Irradiance) cause System Monitor to have black borders around the Resources graphs (Ubuntu 14.04).

**Comment by bsundman** [comment]
Hi, I am not seeing this issue with 14.10 in Unity.  Are you running gnome shell by chance?  I have noticed some other issues like this under gnome shell on Ubuntu while using these themes.  Could you please add a screenshot?  Thanks.

**Comment by dignakov** [comment]
Hi,

No, I'm not running gnome shell, I'm on Ubuntu/Unity. I just tried logging out/in and rebooting with each of your themes, as well as the Ubuntu default themes, Numix, and Flattastic, and I'm only getting the balck borders with Yosembiance/Irradiance. I've attached a picture of what it looks like. Please let me know if there's any info I can give you.
![black_border](https://cloud.githubusercontent.com/assets/810523/5552281/dfa7b934-8bc3-11e4-9ef7-b4d6a1957614.jpg)

**Comment by bsundman** [comment]
Thanks, I will try 14.04 in a VM and see if I can fix this.

**Comment by bsundman** [comment]
I believe I have fixed this bug, please confirm for me.  Thanks!

**Comment by dignakov** [comment]
Thank you! The black borders are gone.
