### ISSUE TITLE
Missing transition animation of a clicked icon on Unity launcher

### ISSUE THREAD

**Issue by chehsunliu** [bsundman/Yosembiance#12]
If I click an icon on the launcher with the default theme, there will be a blink animation indicating the application is loading; otherwise, I'm not sure if the icon is clicked.

**Comment by bsundman** [comment]
Sorry for the late reply.  This is a good point that I have totally missed, will definitely make it on my todo list.

**Comment by bsundman** [comment]
Fixed, let me know if you have any more issues.
