### ISSUE TITLE
Ubuntu 15.10 issues

### ISSUE THREAD

**Issue by kazemnejad** [bsundman/Yosembiance#13]
There is some issues with Ubuntu 15.10:
1- scroll bars:
Yosembiance
![screenshot from 2016-01-05 13-48-41](https://cloud.githubusercontent.com/assets/2122102/12112739/c79f5ed2-b3b3-11e5-8308-b42d13b38722.png)
Radiance
![screenshot from 2016-01-05 13-49-29](https://cloud.githubusercontent.com/assets/2122102/12112740/c7b68e86-b3b3-11e5-94f4-61f42cdc23de.png)

2- Control center:
Yosembiance
![screenshot from 2016-01-05 13-50-46](https://cloud.githubusercontent.com/assets/2122102/12112783/04c2c81c-b3b4-11e5-970a-bd2b52d6e4a4.png)
![screenshot from 2016-01-05 13-51-04](https://cloud.githubusercontent.com/assets/2122102/12112784/04da0a54-b3b4-11e5-9fb2-4f0c0739364c.png)
Radiance
![screenshot from 2016-01-05 13-50-01](https://cloud.githubusercontent.com/assets/2122102/12112797/162daad6-b3b4-11e5-9513-cd8ed7f39bbf.png)
![screenshot from 2016-01-05 13-50-27](https://cloud.githubusercontent.com/assets/2122102/12112798/164303d6-b3b4-11e5-9b9f-850bf3e24962.png)

3- Checkboxes and Radiobuttons:
Yosembiance
![screenshot from 2016-01-05 13-52-01](https://cloud.githubusercontent.com/assets/2122102/12112811/2f4fa960-b3b4-11e5-97d0-69f7c727dd4c.png)
![screenshot from 2016-01-05 13-53-22](https://cloud.githubusercontent.com/assets/2122102/12112812/2f69965e-b3b4-11e5-9bb2-f1536fcfac2c.png)
Radiance
![screenshot from 2016-01-05 13-52-17](https://cloud.githubusercontent.com/assets/2122102/12112817/3d19b716-b3b4-11e5-9320-53c2b865b0fd.png)
![screenshot from 2016-01-05 13-52-57](https://cloud.githubusercontent.com/assets/2122102/12112818/3d2eaba8-b3b4-11e5-9702-53431c56ff9a.png)

tnx

**Comment by bsundman** [comment]
I am currently working on a rewrite for Yosembiance for 15.10.  All of these issues will be fixed along with some small design changes for the next update which will hopefully be released before February.  Thanks for the input.

**Comment by bsundman** [comment]
I have pushed the updates to master for 15.10, let me know if you get a chance to try it.

**Comment by kazemnejad** [comment]
I've just checked latest version. 
thanks for issues, all of them are fixed now!

But there are some notes:
1- Unity launcher is quite nice, i'am fan of it.
2- Selected application in Alt+tab menu is a little bit confusing.
3- New buttons are nice, but i hate their pressed state :)
4- I've noticed that you made windows background a little darker, I personally don't like it.

tnx

**Comment by bsundman** [comment]
Thanks for the input, I'll consider changing some of these things.
