### ISSUE TITLE
Active tab in gnome-terminal hard to distinguish

### ISSUE THREAD

**Issue by nevsnode** [bsundman/Yosembiance#14]
Hi, I am used to have one gnome-terminal window open with a bunch of tabs. Unfortunately it is quite hard to see which of tabs is the current active one:
![screenshot from 2016-01-24 18 53 41](https://cloud.githubusercontent.com/assets/1632219/12537928/6a74e830-c2cc-11e5-829e-ca351de3b734.png)

I'd love to implement that myself and just send a PR, but I'm a complete failure when it comes to making visually appealing things.
Maybe you already have an idea where I could help? ;-)

P.S.: Nice work so far!

**Comment by bsundman** [comment]
Hey, I completely agree with you on the tabs.  I was thinking of doing something more like a smaller Adwaita style, but haven't really made any decisions yet.  If you want to give it a shot, that'd be great.

**Comment by nevsnode** [comment]
Alright, thanks. I'll give it a try.

**Comment by bsundman** [comment]
Check out the tabs I added to Yosembiance-Blue and let me know what you think

**Comment by nevsnode** [comment]
I think it looks pretty nice :thumbsup:

**Comment by bsundman** [comment]
I've added the new tabs to Yosembiance
