### ISSUE TITLE
Menu highlights broken

### ISSUE THREAD

**Issue by konapun** [bsundman/Yosembiance#15]
There is no highlight color when hovering over an item in a menu. In the example below, "New Document" is selected but there is no visual indicator. The screenshot is for the latest yosembiance-blue but regular yosembiance is also broken.

OS: Ubuntu 14.04
GTK version: 3.10.8

![yosembiance-menuselect](https://cloud.githubusercontent.com/assets/498643/12569344/9ec045d6-c393-11e5-8157-e599eb8e5fba.png)

**Comment by bsundman** [comment]
This should be fixed now with the new menus.
