### ISSUE TITLE
Licensing of this theme

### ISSUE THREAD

**Issue by fusion809** [bsundman/Yosembiance#16]
Hi,

I would like to add this theme to the Arch User Repository, but to do this I need to know the license this theme is covered under. Guessing something GPL-compatible?

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Sorry, I just saw the GPL3 license under the debian subfolder. It is now in the [AUR](https://aur.archlinux.org/packages/yosembiance-git).

**Comment by bsundman** [comment]
After looking into it further, I see that Ubuntu's light-themes (Ambiance and Radiance) use the CC-BY-SA-3.0 license.  The only restrictions of this license are that I need to credit the original authors and keep the original license.  I am not really sure where the GPL3 license came from, but it only pertains to the debian packaging of the theme which is not being used by me anymore and will probably be removed in the future.

**Comment by bsundman** [comment]
And thanks for adding to the AUR, Arch is one of my favourite distros :+1:
