### ISSUE TITLE
Evince (and Evince print dialog) and Network Connection Information have black backgrounds

### ISSUE THREAD

**Issue by BlackDex** [bsundman/Yosembiance#19]
Hello,

With all of these nice themes Evince seems to have a lot of black.
Also when i open the "print dialog", the tabs are all out of place and it is all black.
![selection_2016020422 34 38](https://cloud.githubusercontent.com/assets/610450/12830449/aeeecee2-cb8f-11e5-86f9-88a474fa2221.png)

And the Tabs on the Connection Information dialog of the network manager is black.
![selection_2016020422 35 09](https://cloud.githubusercontent.com/assets/610450/12830456/b427218e-cb8f-11e5-94fc-76b8bce8b0bd.png)

All was good at least with commit 12e84aa70e412834fd8b9ad1e722e29124974431
Al tough i wonder for Evince, but it at least was for the connection info dialog.

**Comment by bsundman** [comment]
Thanks for posting this, I'll look into it and try to get a fix as soon as I can.

**Comment by BlackDex** [comment]
Well, i have found the problem of evince my self, and it has nothing to do with the theme.
I have the theme located on a "/data" mount, and symlinked it to my ~/.themes folder.
Evince has an apparmor profile which denied access to the theme.
I changed the apparmor so that it is allowed to access it, and that is fixed.

So the only issue that is still there is the Tabs at the connection information.

( I Stumbled upon this viewing dmesg ;) )

**Comment by bsundman** [comment]
Thank you for the update.  The tabs actually look right as they are based on the color of the titlebar.  It was my first release with the new tabs and I agree that they look a little dark so they may change in the future.

**Comment by BlackDex** [comment]
Oke :) Thx for the update, i have not found it anywhere else where it looks strange i think.
And i like the Atomic theme :).

For me you can close this.
