### ISSUE TITLE
Black tab background in some applications

### ISSUE THREAD

**Issue by kostadinstoilov** [bsundman/Yosembiance#22]
Hi,

Thanks for the great theme. I have noticed a minor problem in some applications - the tabs have a black background, which looks out of place. Screenshot is attached.

I am running a clean install of Ubuntu 16.04. I can help with testing or further debugging the issue.

Thanks.

![yosembiance-black-tabs](https://cloud.githubusercontent.com/assets/5895674/15038802/c7e36680-12af-11e6-9f55-c6a0c9d52509.png)

**Comment by bsundman** [comment]
Hi, glad you like the theme.  The dark tabs were actually meant to be that way and turned out to be an unpopular design choice.  I will be changing it in one of the coming updates.

**Comment by kostadinstoilov** [comment]
Great, thanks!
